SECRET_KEY_BASE:
DEVISE_SECRET_KEY_BASE:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
POSTMARK_API_KEY:
POSTMARK_API_TOKEN:
POSTMARK_INBOUND_ADDRESS:
POSTMARK_SMTP_SERVER:
S3_BUCKET_NAME:
EMAIL_LINK_HOST:
EMAIL_LINK_PROTOCOL:
EMAIL_FROM:
EMAIL_LINK_SUBPATH:
RAILS_RELATIVE_URL_ROOT:
ACTIVATE_PASSBOOK:
PASSBOOK_PASS_TYPE_IDENTIFIER:
APPLE_TEAM_IDENTIFIER:
APPLE_CERTIFICATE_PASSWORD:
ASSET_HOST:
